### ISSUE TITLE
Quick Load: Quick Menu does not reset

### ISSUE THREAD

**Issue by Urinstein** [EpicYoshiMaster/cc-speedrun-utilities#1]
When quick loading out of a situation that blocks some quick menu access, like the food menu during the Apollo fights, it remains blocked.

**Comment by EpicYoshiMaster** [comment]
Fixed! https://github.com/EpicYoshiMaster/cc-speedrun-utilities/commit/fcb61fc4b05928f6bf972e29b5689a66141d3fc0
